/**
 * Landing.tsx — public homepage for DriveReady221.
 *
 * This is the first thing a guest user sees. It's also the page that will
 * appear in FYP report screenshots and the viva demo, so it gets the
 * heaviest visual polish in the Phase-20 redesign.
 *
 * Sections (top → bottom):
 *   1. Hero         — headline + subcopy + dual CTA + product mockup card
 *   2. Stats strip  — quick trust-building numbers
 *   3. Features     — four feature cards covering theory / hazard / AI / booking
 *   4. How it works — 3-step process with numbered indicators
 *   5. Role preview — separate cards for Learner / Instructor / Admin value
 *   6. CTA banner   — final "get started" panel
 *
 * Animation:
 *   Framer Motion is used for staggered entry animations as the user
 *   scrolls each section in. Subtle — no parallax, no wild transforms.
 *   Honours `prefers-reduced-motion` via framer-motion's internal guard.
 *
 * Navigation:
 *   SmartNavbar at the top means a logged-in user still sees their own
 *   role-aware links. Footer stays unchanged.
 */

import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import SmartNavbar from "../components/SmartNavbar";
import Footer from "../components/Footer";
import Card from "../components/ui/Card";

// ---------------------------------------------------------------------------
// Shared content blocks
// ---------------------------------------------------------------------------

// Four headline features. Icons are inline SVGs (no icon library — see
// CLAUDE.md §3.7). Colours match our token palette: blue, amber, indigo,
// green.
const FEATURES = [
  {
    colour: "blue",
    title: "Theory Practice Tests",
    body: "Timed 10-question tests across road signs, speed limits, safety, and motorway rules — same 86% pass mark as the real DVSA test.",
    iconPath:
      "M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25",
  },
  {
    colour: "amber",
    title: "Hazard Perception",
    body: "Spot developing hazards in real driving scenes. Format modelled on the DVSA hazard perception test.",
    iconPath:
      "M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z",
  },
  {
    colour: "indigo",
    title: "AI-Powered Explanations",
    body: "Every wrong answer comes with a plain-English explanation generated by Gemini — cached so you never wait twice.",
    iconPath:
      "M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.814a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456z",
  },
  {
    colour: "green",
    title: "Book a Driving Instructor",
    body: "Search qualified instructors near you, view their availability, and confirm a lesson in one click. Race-safe bookings guaranteed.",
    iconPath:
      "M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5",
  },
];

// Colour classes per feature card. Using a lookup keeps the JSX clean and
// avoids Tailwind purge issues from dynamic strings.
const FEATURE_COLOUR_CLASSES: Record<
  string,
  { bg: string; text: string; glow: string }
> = {
  blue: { bg: "bg-blue-100", text: "text-blue-600", glow: "bg-blue-500/10" },
  amber: { bg: "bg-amber-100", text: "text-amber-600", glow: "bg-amber-500/10" },
  indigo: { bg: "bg-indigo-100", text: "text-indigo-600", glow: "bg-indigo-500/10" },
  green: { bg: "bg-green-100", text: "text-green-600", glow: "bg-green-500/10" },
};

// Role previews — each role card gets its own teaser.
const ROLE_PREVIEWS = [
  {
    role: "Learner",
    headline: "Pass your theory faster.",
    points: [
      "10-question timed theory tests with instant grading",
      "AI explanations for every wrong answer",
      "Hazard perception practice on real scenes",
      "One-click booking with local instructors",
    ],
    cta: { label: "Start as a Learner", to: "/register" },
  },
  {
    role: "Instructor",
    headline: "Fill your diary, not your inbox.",
    points: [
      "Public profile with bio and hourly rate",
      "Self-serve availability management",
      "Automatic booking notifications",
      "Zero double-booking — enforced in the database",
    ],
    cta: { label: "Join as an Instructor", to: "/register" },
  },
  {
    role: "Admin",
    headline: "Manage the whole platform.",
    points: [
      "CRUD for theory and hazard questions",
      "AI assistant for drafting new questions",
      "Per-learner progress drill-down",
      "Platform stats at a glance",
    ],
    cta: { label: "See Admin Features", to: "/login" },
  },
];

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

// Scroll-triggered entry animation. Reused across sections so cards fade +
// rise into place as the user scrolls.
//
// `as const` is required so TypeScript narrows `ease: "easeOut"` and
// `margin: "-80px"` to string literals — framer-motion v12's `Easing` and
// `MarginType` types are literal unions, not plain strings.
const FADE_UP = {
  initial: { opacity: 0, y: 20 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-80px" },
  transition: { duration: 0.55, ease: "easeOut" },
} as const;

export default function Landing() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <SmartNavbar />

      {/* =================================================================
          HERO
          ================================================================= */}
      <section className="relative overflow-hidden pt-14 pb-24 sm:pt-20 sm:pb-32">
        {/* Decorative gradient backdrop — soft, doesn't fight text contrast */}
        <div
          aria-hidden
          className="absolute inset-0 bg-gradient-to-b from-blue-50 via-indigo-50/70 to-transparent"
        />
        <div
          aria-hidden
          className="absolute -top-32 -right-24 w-[500px] h-[500px] rounded-full bg-blue-300/20 blur-3xl"
        />
        <div
          aria-hidden
          className="absolute top-20 -left-20 w-[420px] h-[420px] rounded-full bg-purple-300/20 blur-3xl"
        />

        <div className="relative max-w-6xl mx-auto px-5 sm:px-6 grid lg:grid-cols-2 gap-12 items-center">
          {/* Left — copy + CTAs */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
          >
            <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/70 border border-blue-100 text-xs font-semibold text-blue-700 shadow-sm">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500" />
              UK Driving Theory · Hazard · Instructors
            </span>

            <h1 className="mt-5 text-4xl sm:text-5xl lg:text-6xl font-bold text-gray-900 tracking-tight leading-tight">
              Pass your theory test the{" "}
              <span className="bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 bg-clip-text text-transparent">
                first time.
              </span>
            </h1>

            <p className="mt-5 text-lg text-gray-600 max-w-xl leading-relaxed">
              DriveReady221 combines timed theory practice, hazard
              perception training, AI-powered explanations, and instructor
              booking in a single polished experience.
            </p>

            <div className="mt-8 flex flex-col sm:flex-row gap-3">
              <Link
                to="/register"
                className="inline-flex items-center justify-center gap-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-semibold px-7 py-3.5 rounded-xl shadow-md hover:shadow-lg transition-all"
              >
                Get Started Free
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                </svg>
              </Link>
              <Link
                to="/login"
                className="inline-flex items-center justify-center bg-white hover:bg-gray-50 text-gray-800 font-semibold px-7 py-3.5 rounded-xl border border-gray-200 shadow-sm transition-all"
              >
                Sign In
              </Link>
            </div>

            {/* Tiny trust row */}
            <div className="mt-10 flex items-center gap-6 text-sm text-gray-500">
              <div className="flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4 text-green-600">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                </svg>
                Free to use
              </div>
              <div className="flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4 text-green-600">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                </svg>
                No card required
              </div>
            </div>
          </motion.div>

          {/* Right — mock "quiz preview" card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: "easeOut", delay: 0.15 }}
            className="relative"
          >
            {/* Floating glass panel with a preview of the theory UI */}
            <div className="relative bg-white rounded-3xl shadow-2xl border border-gray-100 p-6 sm:p-7">
              <div className="flex items-center justify-between mb-5">
                <div>
                  <p className="text-xs font-medium text-gray-500">
                    Theory Practice · Question 3 of 10
                  </p>
                  <p className="text-sm font-semibold text-gray-800 mt-1">
                    What does a red-bordered triangular sign mean?
                  </p>
                </div>
                <div className="flex items-center gap-1.5 bg-blue-50 text-blue-700 text-xs font-semibold px-2.5 py-1 rounded-full">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.8} stroke="currentColor" className="w-3.5 h-3.5">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  3:42
                </div>
              </div>

              <div className="space-y-2">
                {[
                  { label: "A. Warning of a hazard ahead", state: "correct" },
                  { label: "B. You must stop immediately", state: "idle" },
                  { label: "C. Road closed to all traffic", state: "idle" },
                  { label: "D. End of priority road", state: "idle" },
                ].map((opt) => (
                  <div
                    key={opt.label}
                    className={`px-4 py-3 rounded-xl border text-sm font-medium transition-colors ${
                      opt.state === "correct"
                        ? "border-green-300 bg-green-50 text-green-800"
                        : "border-gray-200 bg-white text-gray-700"
                    }`}
                  >
                    {opt.label}
                  </div>
                ))}
              </div>

              {/* AI explanation teaser */}
              <div className="mt-5 p-4 rounded-xl bg-gradient-to-br from-indigo-50 via-white to-purple-50 border border-indigo-100">
                <div className="flex items-center gap-2 mb-1.5">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.8} stroke="currentColor" className="w-4 h-4 text-indigo-600">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.814a4.5 4.5 0 00-3.09 3.09z" />
                  </svg>
                  <p className="text-xs font-semibold text-indigo-700">
                    AI Explanation
                  </p>
                </div>
                <p className="text-xs text-gray-600 leading-relaxed">
                  Triangular signs with a red border warn drivers of an
                  upcoming hazard. The specific pictogram inside tells you
                  what kind…
                </p>
              </div>
            </div>

            {/* Subtle outer glow */}
            <div
              aria-hidden
              className="absolute -inset-4 bg-gradient-to-br from-blue-200/40 via-indigo-200/30 to-purple-200/40 blur-2xl -z-10 rounded-[40px]"
            />
          </motion.div>
        </div>
      </section>

      {/* =================================================================
          STATS STRIP — quick credibility
          ================================================================= */}
      <section className="border-y border-gray-100 bg-gray-50/60">
        <div className="max-w-6xl mx-auto px-6 py-8 grid grid-cols-2 sm:grid-cols-4 gap-6 text-center">
          {[
            { value: "45+", label: "Theory questions" },
            { value: "4", label: "Category areas" },
            { value: "86%", label: "DVSA pass mark" },
            { value: "AI", label: "Explanations built-in" },
          ].map((s) => (
            <div key={s.label}>
              <p className="text-2xl sm:text-3xl font-bold text-gray-900">
                {s.value}
              </p>
              <p className="text-xs sm:text-sm text-gray-500 mt-1">
                {s.label}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* =================================================================
          FEATURES — 4-up grid
          ================================================================= */}
      <section className="py-20 sm:py-24">
        <div className="max-w-6xl mx-auto px-5 sm:px-6">
          <motion.div {...FADE_UP} className="text-center mb-14">
            <p className="text-sm font-semibold text-blue-600 uppercase tracking-wider">
              Everything you need
            </p>
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mt-2 tracking-tight">
              Built for the UK driving test, end-to-end.
            </h2>
            <p className="text-gray-500 mt-3 max-w-2xl mx-auto">
              Theory practice, hazard perception, AI feedback, and instructor
              booking — no plugins, no extra apps.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {FEATURES.map((f, i) => {
              const c = FEATURE_COLOUR_CLASSES[f.colour];
              return (
                <motion.div
                  key={f.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-60px" }}
                  transition={{ duration: 0.45, delay: i * 0.08 }}
                >
                  <Card hover className="p-6 h-full">
                    <div
                      className={`${c.bg} ${c.text} rounded-xl w-11 h-11 flex items-center justify-center mb-4`}
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.8} stroke="currentColor" className="w-5 h-5">
                        <path strokeLinecap="round" strokeLinejoin="round" d={f.iconPath} />
                      </svg>
                    </div>
                    <h3 className="text-base font-semibold text-gray-900 mb-2">
                      {f.title}
                    </h3>
                    <p className="text-sm text-gray-500 leading-relaxed">
                      {f.body}
                    </p>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* =================================================================
          HOW IT WORKS — 3-step process
          ================================================================= */}
      <section className="py-20 bg-gradient-to-b from-gray-50 to-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-6">
          <motion.div {...FADE_UP} className="text-center mb-14">
            <p className="text-sm font-semibold text-indigo-600 uppercase tracking-wider">
              How it works
            </p>
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mt-2 tracking-tight">
              Three steps to test day.
            </h2>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              {
                step: "01",
                title: "Create your free account",
                body: "Sign up as a learner or an instructor. Email verification keeps spam accounts out.",
              },
              {
                step: "02",
                title: "Practise & learn",
                body: "Take timed theory and hazard tests. Ask AI for a plain-English explanation on any wrong answer.",
              },
              {
                step: "03",
                title: "Book your lessons",
                body: "Search instructors near you, see their live availability, and lock in a slot instantly.",
              },
            ].map((s, i) => (
              <motion.div
                key={s.step}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-60px" }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className="relative"
              >
                <Card className="p-6 sm:p-7 h-full">
                  <span className="text-xs font-bold text-blue-600 tracking-widest">
                    STEP {s.step}
                  </span>
                  <h3 className="text-lg font-semibold text-gray-900 mt-2">
                    {s.title}
                  </h3>
                  <p className="text-sm text-gray-500 mt-2 leading-relaxed">
                    {s.body}
                  </p>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* =================================================================
          ROLE PREVIEWS — Learner / Instructor / Admin
          ================================================================= */}
      <section className="py-20 sm:py-24">
        <div className="max-w-6xl mx-auto px-5 sm:px-6">
          <motion.div {...FADE_UP} className="text-center mb-14">
            <p className="text-sm font-semibold text-purple-600 uppercase tracking-wider">
              Built for every role
            </p>
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mt-2 tracking-tight">
              Learners, instructors, and admins — all in one platform.
            </h2>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {ROLE_PREVIEWS.map((r, i) => (
              <motion.div
                key={r.role}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-60px" }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
              >
                <Card hover className="p-6 sm:p-7 h-full flex flex-col">
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-xs font-bold text-gray-400 uppercase tracking-widest">
                      For {r.role}s
                    </span>
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">
                    {r.headline}
                  </h3>
                  <ul className="space-y-2 text-sm text-gray-600 flex-1">
                    {r.points.map((p) => (
                      <li key={p} className="flex items-start gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2.2} stroke="currentColor" className="w-4 h-4 text-green-500 flex-shrink-0 mt-0.5">
                          <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                        </svg>
                        <span>{p}</span>
                      </li>
                    ))}
                  </ul>
                  <Link
                    to={r.cta.to}
                    className="mt-5 inline-flex items-center gap-1.5 text-sm font-semibold text-blue-600 hover:text-blue-700"
                  >
                    {r.cta.label}
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                    </svg>
                  </Link>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* =================================================================
          FINAL CTA — gradient banner
          ================================================================= */}
      <section className="pb-20 sm:pb-24">
        <div className="max-w-5xl mx-auto px-5 sm:px-6">
          <motion.div
            {...FADE_UP}
            className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-blue-600 via-indigo-700 to-purple-700 text-white px-6 sm:px-12 py-12 sm:py-16 text-center"
          >
            <div
              aria-hidden
              className="absolute -top-24 -left-24 w-72 h-72 rounded-full bg-white/10 blur-3xl"
            />
            <div
              aria-hidden
              className="absolute -bottom-20 -right-12 w-72 h-72 rounded-full bg-purple-400/20 blur-3xl"
            />

            <h2 className="relative text-3xl sm:text-4xl font-bold tracking-tight">
              Ready to prepare for your driving test?
            </h2>
            <p className="relative mt-3 text-blue-100 max-w-xl mx-auto">
              Sign up in 30 seconds. Practise at your own pace. Book lessons
              when you're ready.
            </p>
            <div className="relative mt-8 flex flex-col sm:flex-row items-center justify-center gap-3">
              <Link
                to="/register"
                className="inline-flex items-center justify-center bg-white text-blue-700 font-semibold px-8 py-3.5 rounded-xl shadow-md hover:shadow-lg transition-all"
              >
                Create Your Free Account
              </Link>
              <Link
                to="/faq"
                className="inline-flex items-center justify-center text-white/90 hover:text-white font-medium px-5 py-3.5"
              >
                Read the FAQ →
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
